version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
    - "8001:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
  app:
    build: app/
    ports:
    - "8000:8000"
    depends_on:
      - db